services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      #- HARPERDB_URL=http://your-harperdb-url
      #- HARPERDB_PW=your-harperdb-password
    ports:
      - 5000:5000